ServerEvents.recipes(e => {

    e.shapeless('1x kubejs:netherite_greatsword', ['kubejs:diamond_greatsword', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_greatsword', [' M ', 'M M', ' W '], {M: 'minecraft:diamond', W: 'minecraft:diamond_sword'})
    e.shaped('kubejs:iron_greatsword', ['M', 'M M', ' W '], {M: 'minecraft:iron_ingot', W: 'minecraft:iron_sword'})
    e.shaped('kubejs:stone_greatsword', [' M ', 'M M', ' W '], {M: 'minecraft:cobblestone', W: 'minecraft:stone_sword'})
    e.shaped('kubejs:wooden_greatsword', [' M ', 'M M', ' W '], {M: '#minecraft:planks', W: 'minecraft:wooden_sword'})
    e.shaped('kubejs:golden_greatsword', [' M ', 'M M', ' W '], {M: 'minecraft:gold_ingot', W: 'minecraft:golden_sword'})

    e.shapeless('1x kubejs:netherite_spear', ['kubejs:diamond_spear', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_spear', ['  M', ' S ', 'S  '], {M: 'minecraft:diamond', S: 'minecraft:stick'})
    e.shaped('kubejs:iron_spear', ['  M', ' S ', 'S  '], {M: 'minecraft:iron_ingot', S: 'minecraft:stick'})
    e.shaped('kubejs:stone_spear', ['  M', ' S ', 'S  '], {M: 'minecraft:cobblestone', S: 'minecraft:stick'})
    e.shaped('kubejs:wooden_spear', ['  M', ' S ', 'S  '], {M: '#minecraft:planks', S: 'minecraft:stick'})
    e.shaped('kubejs:golden_spear', ['  M', ' S ', 'S  '], {M: 'minecraft:gold_ingot', S: 'minecraft:stick'})

    e.shapeless('1x kubejs:netherite_dagger', ['kubejs:diamond_dagger', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_dagger', ['   ', 'SMS', ' S '], {M: 'minecraft:diamond', S: 'minecraft:stick'})
    e.shaped('kubejs:iron_dagger', ['   ', 'SMS', ' S '], {M: 'minecraft:iron_ingot', S: 'minecraft:stick'})
    e.shaped('kubejs:stone_dagger', ['   ', 'SMS', ' S '], {M: 'minecraft:cobblestone', S: 'minecraft:stick'})
    e.shaped('kubejs:wooden_dagger', ['   ', 'SMS', ' S '], {M: '#minecraft:planks', S: 'minecraft:stick'})
    e.shaped('kubejs:golden_dagger', ['   ', 'SMS', ' S '], {M: 'minecraft:gold_ingot', S: 'minecraft:stick'})

    e.shapeless('1x kubejs:netherite_kopesh', ['kubejs:diamond_kopesh', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_kopesh', ['  M', ' M ', ' S '], {M: 'minecraft:diamond', S: 'minecraft:stick'})
    e.shaped('kubejs:iron_kopesh', ['  M', ' M ', ' S '], {M: 'minecraft:iron_ingot', S: 'minecraft:stick'})
    e.shaped('kubejs:stone_kopesh', ['  M', ' M ', ' S '], {M: 'minecraft:cobblestone', S: 'minecraft:stick'})
    e.shaped('kubejs:wooden_kopesh', ['  M', ' M ', ' S '], {M: '#minecraft:planks', S: 'minecraft:stick'})
    e.shaped('kubejs:golden_kopesh', ['  M', ' M ', ' S '], {M: 'minecraft:gold_ingot', S: 'minecraft:stick'})

    e.shapeless('1x kubejs:netherite_glaive', ['kubejs:diamond_glaive', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_glaive', [' M ', 'MWM', ' S '], {M: 'minecraft:diamond', S: 'minecraft:stick', W: 'minecraft:diamond_axe'})
    e.shaped('kubejs:iron_glaive', [' M ', 'MWM', ' S '], {M: 'minecraft:iron_ingot', S: 'minecraft:stick', W: 'minecraft:iron_axe'})
    e.shaped('kubejs:stone_glaive', [' M ', 'MWM', ' S '], {M: 'minecraft:cobblestone', S: 'minecraft:stick', W: 'minecraft:stone_axe'})
    e.shaped('kubejs:wooden_glaive', [' M ', 'MWM', ' S '], {M: '#minecraft:planks', S: 'minecraft:stick', W: 'minecraft:wooden_axe'})
    e.shaped('kubejs:golden_glaive', [' M ', 'MWM', ' S '], {M: 'minecraft:gold_ingot', S: 'minecraft:stick', W: 'minecraft:golden_axe'})

    e.shapeless('1x kubejs:netherite_greataxe', ['kubejs:diamond_greataxe', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_greataxe', [' M ', 'MW ', ' S '], {M: 'minecraft:diamond', S: 'minecraft:stick', W:'minecraft:diamond_axe'})
    e.shaped('kubejs:iron_greataxe', [' M ', 'MW ', ' S '], {M: 'minecraft:iron_ingot', S: 'minecraft:stick', W:'minecraft:iron_axe'})
    e.shaped('kubejs:stone_greataxe', [' M ', 'MW ', ' S '], {M: 'minecraft:cobblestone', S: 'minecraft:stick', W:'minecraft:stone_axe'})
    e.shaped('kubejs:wooden_greataxe', [' M ', 'MW ', ' S '], {M: '#minecraft:planks', S: 'minecraft:stick', W:'minecraft:wooden_axe'})
    e.shaped('kubejs:golden_greataxe', [' M ', 'MW ', ' S '], {M: 'minecraft:gold_ingot', S: 'minecraft:stick', W:'minecraft:golden_axe'})

    e.shapeless('1x kubejs:netherite_greathammer', ['kubejs:diamond_greathammer', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_greathammer', ['NMN', ' S ', ' S '], {M: 'minecraft:diamond_block', S: 'minecraft:stick', N: 'minecraft:obsidian'})
    e.shaped('kubejs:iron_greathammer', ['NMN', ' S ', ' S '], {M: 'minecraft:iron_block', S: 'minecraft:stick', N: 'minecraft:obsidian'})
    e.shaped('kubejs:stone_greathammer', ['NMN', ' S ', ' S '], {M: 'minecraft:cobblestone', S: 'minecraft:stick', N: 'minecraft:obsidian'})
    e.shaped('kubejs:wooden_greathammer', ['NMN', ' S ', ' S '], {M: '#minecraft:planks', S: 'minecraft:stick', N: 'minecraft:obsidian'})
    e.shaped('kubejs:golden_greathammer', ['NMN', ' S ', ' S '], {M: 'minecraft:gold_block', S: 'minecraft:stick', N: 'minecraft:obsidian'})

    e.shapeless('1x kubejs:netherite_katana', ['kubejs:diamond_katana', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_katana', ['  M', ' M ', ' W '], {M: 'minecraft:diamond', W: 'kubejs:diamond_kopesh'})
    e.shaped('kubejs:iron_katana', ['  M', ' M ', ' W '], {M: 'minecraft:iron_ingot', W: 'kubejs:iron_kopesh'})
    e.shaped('kubejs:stone_katana', ['  M', ' M ', ' W '], {M: 'minecraft:cobblestone', W: 'kubejs:stone_kopesh'})
    e.shaped('kubejs:wooden_katana', ['  M', ' M ', ' W '], {M: '#minecraft:planks', W: 'kubejs:wooden_kopesh'})
    e.shaped('kubejs:golden_katana', ['  M', ' M ', ' W '], {M: 'minecraft:gold_ingot', W: 'kubejs:golden_kopesh'})

    e.shapeless('1x kubejs:netherite_rapier', ['kubejs:diamond_rapier', 'minecraft:netherite_ingot', 'minecraft:netherite_upgrade_smithing_template'])
    e.shaped('kubejs:diamond_rapier', [' M ', 'SMS', ' S '], {M: 'minecraft:diamond', S: 'minecraft:stick'})
    e.shaped('kubejs:iron_rapier', [' M ', 'SMS', ' S '], {M: 'minecraft:iron_ingot', S: 'minecraft:stick'})
    e.shaped('kubejs:stone_rapier', [' M ', 'SMS', ' S '], {M: 'minecraft:cobblestone', S: 'minecraft:stick'})
    e.shaped('kubejs:wooden_rapier', [' M ', 'SMS', ' S '], {M: '#minecraft:planks', S: 'minecraft:stick'})
    e.shaped('kubejs:golden_rapier', [' M ', 'SMS', ' S '], {M: 'minecraft:gold_ingot', S: 'minecraft:stick'})
})